export const FETCH_FLOW = 'FETCH_FLOW';
export const FETCH_CHOICE = 'FETCH_CHOICE';
export const CHANGE_CURRENT = 'CHANGE_CURRENT';
export const INITIALISE_INSTANT_DATA = 'INITIALISE_INSTANT_DATA';
export const CHANGE_INSTANT_DATA = 'CHANGE_INSTANT_DATA';
export const SET_MAX = 'SET_MAX';